name: Build and Test

on:
  push:
    branches: [ main ]  # Trigger on push to the main branch
  pull_request:
    branches: [ main ] # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Action to checkout your repository code

    - name: Run Makefile build and test
      run: make all
